openapi: "3.0.3"
info: 
  version: 1.0.0
  title: Swagger VK API
  license:
    name: MIT
  contact: 
    email: dmtheory@gmail.com
    name: Andrey
servers: 
    - url: http://localhost:4040/v1
    - url: http://localhost:2000/v1
    - url: http://localhost:2000/v2
paths:
    /friends:
      get:
        summary: Получить список друзей текущего пользователя
        responses:
          '200':
            description: Список получен
            content: 
              application/json: 
                schema:
                  type: array
                  items: 
                    type: object
                    properties: 
                      id: 
                        type: integer
                      name: 
                        type: string
                    required: 
                      - id
                      - name
          '400':
              description: Ошибка в данных
          '401':
              description: Пользователь не авторизован
          '403':
              description: Недостаточно прав
          '429':
              description: Превышен лимит запросов
      post: 
        summary: Добавление друга
        requestBody:
            required: true
            content: 
              application/json: 
                schema:
                    type: object
                    properties:
                      friend_id:
                          type: integer
                          example: 123456
                    required:
                        - friend_id
        responses:
            '201':
                description: Друг успешно добавлен
            '400':
                description: Ошибка в данных
            '401':
                description: Пользователь не авторизован
            '403':
                description: Недостаточно прав
            '404':
                description: Пользователь не существует
            '409':
                description: Вы уже друзья
            '429':
                description: Превышен лимит запросов
    /friends/{user_id}:
      get:
        summary: Получить список друзей определенного пользователя
        parameters:
          - name: user_id
            in: path
            required: true
            schema:
              type: integer
              example: 444555666
            description: Идентификатор пользователя
        responses:
          '200':
            description: Список получен
          '400':
              description: Ошибка в данных
          '401':
              description: Пользователь не авторизован
          '403':
              description: Недостаточно прав
          '404':
              description: Пользователь не существует
          '429':
              description: Превышен лимит запросов
      delete:
        summary: Удалить из друзей
        parameters:
          - name: user_id
            in: path
            required: true
            schema:
              type: integer
              example: 123456
            description: Идентификатор пользователя, которого нужно удалить из друзей
        responses:
          '200':
            description: Друг удален
          '400':
              description: Ошибка в данных
          '401':
              description: Пользователь не авторизован
          '403':
              description: Недостаточно прав
          '404':
              description: Пользователь не существует
          '409':
              description: Вы не друзья
          '429':
              description: Превышен лимит запросов
    /page/{user_id}:
      get:
        summary: Просмотр анкеты пользователя
        parameters:
          - name: user_id
            in: path
            required: true
            schema:
              type: integer
              example: 77782819
            description: Идентификатор пользователя
        responses: 
          '200':
            description: анкета пользователя получена
          '400':
              description: Ошибка в данных
          '401':
              description: Пользователь не авторизован
          '403':
              description: Недостаточно прав
          '404':
              description: Пользователь не существует
          '429':
              description: Превышен лимит запросов
    /feed:
      post: 
        summary: Публикация поста в ленту
        description: |
          Пост должен содержать хотя бы одно из: текст или медиафайлы. 
          Если оба поля пустые или отсутствуют, сервер вернёт 400 Bad Request.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    text:
                        type: string
                        example: Привет это мой первый пост
                    media:
                      type: array
                      items:
                        type: string 
                      example: ["image1.jpg","image2.jpg"]
        responses:
          '201':
            description: Пост опубликован
            content: 
              application/json: 
                schema:
                  type: object
                  properties: 
                    text:
                      type: string 
                      example: "Мы здесь живем"
                    id:
                      type: integer
                      example: 1 
                    media:
                      type: array
                      items: 
                        type: string 
                        example: ["img1.jpg", "img2.jpg"]
                  required:
                    - id
          '400':
            description: Ошибка в данных
          '401':
              description: Пользователь не авторизован
          '403':
              description: Недостаточно прав
      get: 
        summary: Получение ленты текущего пользователя
        parameters:
          - name: limit
            in: query
            schema: 
              type: integer 
              example: 20
          - name: offset
            in: query 
            schema:
              type: integer 
              example: 0
        responses:
          '200':
            description: Лента получена
            content: 
              application/json: 
                schema:
                  type: array
                  items: 
                    type: object
                    properties: 
                      text:
                        type: string 
                        example: "Мы здесь живем"
                      id:
                        type: integer
                        example: 1 
                      media:
                        type: array
                        items: 
                          type: string 
                          example: ["img1.jpg", "img2.jpg"]
                    required:
                      - id
          '400':
            description: Ошибка в данных
          '401':
              description: Пользователь не авторизован
          '403':
              description: Недостаточно прав
    /media:
      post:
        summary: Загрузка контента
        requestBody: 
          required: true
          content:
            multipart/form-data:
              schema: 
                type: object 
                properties: 
                  file:
                    type: string 
                    format: binary
                required:
                  - file
        responses:
          '201':
            description: Контент успешно загружен
            content:
              application/json:
                schema:
                  type: object 
                  properties: 
                    media_id:
                      type: string
                      example: "abc123"
                    media_url:
                      type: string
                      example: "https://example.com/uploads/abc12.jpg"
                  required: 
                    - media_url
                    - media_id
    /feed/{user_id}:
      get: 
        summary: Просмотр ленты постов
        parameters: 
          - name: user_id
            in: path
            required: true
            schema:
              type: integer 
              example: 1234567
          - name: limit
            in: query
            schema:
              type: integer
              example: 0
          - name: offset
            in: query
            schema:
              type: integer 
              example: 5
        responses:
          '200':
            description: Посты получены
            content: 
              application/json: 
                schema:
                  type: array
                  items: 
                    type: object
                    properties: 
                      text:
                        type: string 
                        example: "Мы здесь живем"
                      id:
                        type: integer
                        example: 1 
                      media:
                        type: array
                        items: 
                          type: string 
                          example: ["img1.jpg", "img2.jpg"]
                    required:
                      - id

